### ISSUE TITLE
Impossible to fork and build

### ISSUE THREAD

**Issue by sebastienfi** [ajainvivek/react-aztec#3]
Could you please detail the procedure to build and test a forked version of your repo ?

I did this but it leads to the below error 

*  Forked the repo
*  Made the changes I needed
*  Removed the `src/` in `.npmignore` and `.gitignore`
*  Installed using my repo version of the fork (`npm i --save git+https://git@github.com/MichaelDM/react-aztec.git`)

```
Failed to compile.

Error in ./~/react-aztec/dist-modules/components/controls/index.js
Module not found: [CaseSensitivePathsPlugin] `my-path-to-app\node_modules\react-aztec\dist-modules\components\controls\TextField.js` does not match the corresponding path on disk `Textfield.js`.

 @ ./~/react-aztec/dist-modules/components/controls/index.js 7:17-39
```

Please advise

**Comment by ajainvivek** [comment]
@sebastienfi Can you please clone the repo and check if everything works? If it is a problem with repo then I need to investigate in my spare time.

**Comment by sebastienfi** [comment]
```
git clone git@github.com:ajainvivek/react-aztec.git
cd react-aztec
npm i
npm run start
```

Then I see a bunch of errors like these : 
```
31:25  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
✖ 31 problems (31 errors, 0 warnings)
```
So I deactivated the linter feature for my environment. The linter should be advising, not preventing to build.

```json
module.exports = {
  "extends": "airbnb",
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true,
    "mocha": true
  },
  "plugins": [
    "react"
  ],
  "rules": {
    "comma-dangle": 0,
    "prefer-arrow-callback": 0,
    "func-names": 0,
    "import/no-extraneous-dependencies": 0,
    "no-underscore-dangle": 0,
    "no-unused-expressions": 0,
    "no-unused-vars": 0,
    "no-use-before-define": 0,
    "react/sort-comp": 0,
    "react/no-multi-comp": 0,
    "react/require-extension": 0,
    "react/jsx-uses-react": 0,
    "react/forbid-prop-types": 0,
    "react/no-unused-prop-types": 0,
    "linebreak-style": 0,
    "comma-dangle": 0,
    "max-len": 0,
    "import/imports-first": 0,
    "class-methods-use-this": 0,
    "semi": 0,
    "react/jsx-filename-extension": 0,
    "space-before-blocks": 0,
    "space-infix-ops": 0,
    "react/jsx-closing-bracket-location": 0,
    "react/jsx-first-prop-new-line": 0,
    "no-nested-ternary": 0,
    "import/no-unresolved": 0,
    "import/extensions": 0,
    "arrow-body-style": 0,
    "no-param-reassign": 0,
  }
};
```

Then I can make changes to the radio component, let's say, to add the possibility to include an image istead of only just text. On rebuild I will have an updated set of components, or I can just run `npm run dist`.

Then how do I get this components installed to my local site ? Does it necessary have to go through you publishing an updated version of the NPM package ? Should I add a watch command that will take the updated modules and copy it to my node_modules ? Or maybe using webpack and it's out-dir parameter to output to my site ?

**Comment by sebastienfi** [comment]
This is the error I have
```javascript
Error in ./~/react-aztec/dist-modules/components/controls/index.js
Module not found: [CaseSensitivePathsPlugin] `C:\...\My-App\node_modules\react-aztec\dist-modules\components\controls\TextField.js` does not match the corresponding path on disk `Textfield.js`.

 @ ./~/react-aztec/dist-modules/components/controls/index.js 7:17-39
```

I PRed to solve this.

**Comment by ajainvivek** [comment]
I have merged the PR and bumped the package version. Closing the ticket off for now
