### ISSUE TITLE
Replacing pui-react-grids with react-flexbox-grid?

### ISSUE THREAD

**Issue by code-propagator** [ajainvivek/react-aztec#7]
I found pui-react-grids doesn't work well for resizing views and this module causes pollution for global GUI styles.
I tried replacing pui-react-grids with react-flexbox-grid, which is better for local layout with Material-UI components.
However linking modified react-aztec as local-module fails.
How to make react-flexbox-grid version of Aztec?

**Comment by code-propagator** [comment]
I've just succeeded to eliminate pui-react-grids without any modification with react-aztec module.
Taking a copy of Aztec.jsx file to my project and modify the definition of Row, Col for react-flexbox-grid was enough. The react-aztec is installed into node_module without any modifications.

Thank you.

**Comment by ajainvivek** [comment]
@code-propagator It would be great, if you could raise a PR for replacing pui-react-grids with react-flexbox-grid. That would be wonderful 👍

**Comment by code-propagator** [comment]
Thank you for a comment. Essentially in Aztec.jsx, only import lines were adjusted as follows.
For react-flexbox-grid, the Aztec form should be wrapped with <Grid><Aztec.../></Grid>.
Layout uses 12 basis grid columns instead of 24. That's all. 
--- [copy of Aztex.jsx] ---
// import { Row, Col } from 'pui-react-grids'
import { Row, Col } from 'react-flexbox-grid'

import { DynamicComponent } from 'react-aztec/dist-modules/components/DynamicComponent'
import { generateLayout } from 'react-aztec/dist-modules/helpers/filter'
import mui from 'react-aztec/dist-modules/config/mui'
import validation from 'react-aztec/dist-modules/helpers/validation'


I like react-aztec better than redux-form. 
The redux-form is not designed for multiple instances of a same form, needs tedious work for redux-form users.

Thank you!
